### ISSUE TITLE
Copying, searching for and pasting two lines of text causes a crash

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#10002]
I'm on the latest beta, but this also happened in the previous build I was using, from July.
To reproduce this, open a subtitle file that contains a subtitle with two lines of text text. My sample file looks like this:

<img width="977" height="700" alt="Image" src="https://github.com/user-attachments/assets/ff73df43-be81-4ff6-9527-5b72549d8d9c" />

Focus the textbox for the subtitle and select its contents. Use ctrl+C to copy the text. Now press the keyboard shortcut for `Find`. Use ctrl+V to paste the text (though it's already there). You'll see the following:

<img width="977" height="699" alt="Image" src="https://github.com/user-attachments/assets/472009b2-af8e-496e-a97f-83bb3ee96414" />

Note that both lines of text are in the input field. Press enter or click `Find next`:

<img width="976" height="699" alt="Image" src="https://github.com/user-attachments/assets/73921aa1-9c50-49ba-8a26-806973e130d4" />

Note that the status bar is now two lines tall rather than one, to accommodate both lines of text.
Close the `Find` window by pressing escape. You'll now be in the textbox again with the text selected:

<img width="976" height="699" alt="Image" src="https://github.com/user-attachments/assets/7adf3ef5-7475-4de7-af49-0921fc8e93f9" />

Now press ctrl+V again. The program will crash.

I suspect this has to do with what happens to the status bar, since if you do anything to reset the status bar to a single line, no crash occurs. Also, it's best to test this with a large or maximized window, since it apparently doesn't happen if the window is very small.

Here's everything together as a gif:

![Image](https://github.com/user-attachments/assets/38ae1c5e-0762-4139-8949-bfd240f2cff6)

**Comment by niksedk** [comment]
Thx for the nicely explained bug report! :)

Hopefully fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.13/SubtitleEditBeta.zip

Also, I'm mostly working on SE 5 now - still in the early preview phase, but it's getting better slowly: https://github.com/niksedk/subtitleedit-avalonia/releases

**Comment by darnn** [comment]
Still happens, unfortunately.

And since you asked:
General: Merge with next, Merge original and translation, Switch original and translation, Go to current line start/end, Cycle audio tracks, Choose profile
File: Save all, Import -> Plain Text, Right to left
Tools: Remove text for hearing impaired, Change casing, Make new empty translation from current subtitle
Video: One frame back/forward, 500 ms back/forward, One second back/forward, Fullscreen, Play rate slower/faster
Synchronization: Adjust all times
List view and text box: Insert before/after
List view: Toggle focus between list view and subtitle text box (so in this case between the subtitle grid and the text box), Copy text from original to current, all the Column shortcuts
Text box: Split line at cursor position, Split line at cursor/video position, Move last word to/Fetch first word from next subtitle
Create/adjust: Set end and go to next, Set end, next start and go to next

**Comment by niksedk** [comment]
OK, SE 5 preview 47 now have the shortcuts you requested:  https://github.com/niksedk/subtitleedit-avalonia/releases
:)

Also, yet another try for fixing this crash SE4: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.13/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Still happening, I'm afraid.

And that's very kind of you! I'll set them all up and give it a proper try.

**Comment by ivandrofly** [comment]
It all starts once the live-spell-check fires event.

Another another interesting thing is this method her (image)

<img width="1258" height="520" alt="Image" src="https://github.com/user-attachments/assets/5f79e92e-20a2-4d1b-8063-1c3a03197edf" />

When you check  `_uiTextBox?.IsDispose` it will be `false` but inside the method `InitializeLiveSpellCheck` `_uiTextBox?.IsDisposed` will be
`true`

I've also noticed some calls coming from wndproc method

ps: if you want a quick fix just comment out the `.Dispose()` but I'm still investigating the reason why the state change while we are inside the `InitializeLiveSpellCheck`

**Comment by darnn** [comment]
@niksedk I realize it's not in beta yet, but I've been trying to test Avalonia, and have hit a bug that makes it pretty hard to do anything. One way to reproduce it is open a video with subtitles (with `Select current subtitle while playing` on), start playing it, open and close settings, and then open shortcuts and leave it open. After a few seconds it starts going back and forth between whatever subtitle it was on and a different subtitle and becomes unresponsive.

**Comment by ivandrofly** [comment]
> and then open shortcuts and leave it open

From what menu?

**Comment by ivandrofly** [comment]
> [@niksedk](https://github.com/niksedk) I realize it's not in beta yet, but I've been trying to test Avalonia, and have hit a bug that makes it pretty hard to do anything. One way to reproduce it is open a video with subtitles (with `Select current subtitle while playing` on), start playing it, open and close settings, and then open shortcuts and leave it open. After a few seconds it starts going back and forth between whatever subtitle it was on and a different subtitle and becomes unresponsive.

it's better to open a new github issue as this issue is now closed
