### ISSUE TITLE
more SHD removal stuff

### ISSUE THREAD

**Issue by Thunderbolt8** [SubtitleEdit/subtitleedit#1429]
some more SHD removal stuff:

In this case the hyphen in front of RECORDING should not be removed, because its used to distinguish the speaker 1 "have your lost someone" from speaker 2 "what?" (the black dot is supposed to be a hyphen again):

- RECORDING: < i >Have you lost someone?< /i >|- What?

==> < i >Have you lost someone?< /i >|- What?

strangely enough it already works in this case, dont know whats the difference between these two cases:

- WOMAN: < i >Hello?< /i >|- Hello. Angel?

==> < i >- Hello?< /i >|- Hello. Angel?

----------------------------------------------------------------------------
some minor fix/addition to one of the last fixes

"in such a case here, if SHD information gets removed and a hyphen ("—" "-" or "--") follows afterwards, a syntactic indicator of ending or linking a sentence like full stop (.), exclamation mark (!) or comma (,) which directly preceeds that SHD information should be removed then.

Oh. Oh, yeah. Um — ==> Yeah. — (Should be: Yeah —)"

She uh...|She disappeared.

==> She |She disappeared.

triple dots "..." should be excluded from this as they inform on the speech act or state of mind (thinking) of a person. 

==> She...|she disappeared

the initial letter of the word following after that (in case its still the same speaker, so if theres no hyphen (at the beginning of the next part of the line) following after that) should not be uppercase then.

**Comment by Thunderbolt8** [comment]
dont know if you still working on this (downloaded the latest zip and tested), but in case of the 2nd example the "She" after the line break is still displayed with initial uppercase character.

the other issue is fixed, thanks!

**Comment by niksedk** [comment]
Not really sure when the beta zip got updated... but it's updated now: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.4.10/SubtitleEditBetaTest.zip
How does it work for you?

**Comment by Thunderbolt8** [comment]
same as before, "She" is still uppercase

**Comment by niksedk** [comment]
@Thunderbolt8: This is fixed now, right?

**Comment by Thunderbolt8** [comment]
I cant find the subtitle file with this error. but last time I checked this part

"the initial letter of the word following after that (in case its still the same speaker, so if theres no hyphen (at the beginning of the next part of the line) following after that) should not be uppercase then."

was not fixed yet. The rest is.

**Comment by niksedk** [comment]
This works here:
"She uh...|she disappeared." => "She uh...|she disappeared."

**Comment by xylographe** [comment]
I think, Thunderbolt8 expects:

- `She uh...|She disappeared.` ==> `She...|she disappeared.`
 (second upper case `S` converted to lower case)

- `She uh...|- She disappeared.` ==> `She...|- She disappeared.`
 (no case conversion, because speaker has changed)

**Comment by Thunderbolt8** [comment]
I havent even checked if the speaker actually changes here with the audio but from what I can remember in this track there would have been a hyphen at the beginning of that 2nd line if the speaker had changed. so no change of speaker here.

"She uh...|she disappeared." => "She uh...|she disappeared."

wheres the difference in this? The original
