### ISSUE TITLE
Subtitles position in webvtt

### ISSUE THREAD

**Issue by Plazik** [SubtitleEdit/subtitleedit#2296]
Hello,

Is it possible to add support of subtitle possition in webvtt (Netflix)? Similar to https://github.com/SubtitleEdit/subtitleedit/issues/2190.

Examples:
```
121
00:08:08.621 --> 00:08:09.789  position:50.00%,middle  align:middle size:80.00%  line:84.67% 
Да?

122
00:08:09.922 --> 00:08:16.696  position:50.00%,middle  align:middle size:80.00%  line:10.00% 
Я вернулся, чтобы спросить, не хочешь
ли ты вернуться к Фреду Эндрюсу.
```

`line:84.67%` - bottom, `line:10.00%` - top.

Subtitles:
https://mega.nz/#!VIdwSDTJ!2HV70j5K0eh4wMcFLSVHJJmHCJPB6vsJgiUljLO-k2k

**Comment by niksedk** [comment]
@Plazik: I've given it a try here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip
How does it work?

**Comment by Plazik** [comment]
Hmm, it doesn't work for me.

I've opened .vtt file and saved it as .ASS. The resulting file don't have subtitles position.

I've also checked https://github.com/SubtitleEdit/subtitleedit/issues/2190 in this beta version - it stopped working for me too. The latest stable 3.5.2 works fine for me...

**Comment by niksedk** [comment]
Give you give a specific line that does not work for you?
Line 31 gives this: `{\an8}ОРИГИНАЛЬНЫЙ СЕРИАЛ NETFLIX`

#2190 re-fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

**Comment by Plazik** [comment]
All lines don't work for me...

Is any addition steps required?

Here is my source files:
https://mega.nz/#!dF0yHaRA!PC2iHDsyJCjHCd3e1Ue_BtPmdPg_CJLe6I-Qurv24-o
https://mega.nz/#!gA8ngCjB!QhmNTrurzRCydle4-CBstGbrnwgsWaJZEU1sycya3pU 

I've opened these files in the latest beta, Save as .ASS files:
https://mega.nz/#!0MNzhaJC!XNGZzN8WKZsXHBg4A_rbwOQUjBaq0Sn3vzvo9TslxNs
https://mega.nz/#!BFMWSQhI!2XmvHXzTsXgPCFi0n3-Puefvyj9C1UhgrauwiFeIeTQ

They don't have any `{\an8}` symbols.

**Comment by niksedk** [comment]
OK, for what lines did you expect an `{\an8}` tag for?

**Comment by Plazik** [comment]
Like these:

```
188
00:09:40.079 --> 00:09:41.681  position:50.00%,middle  align:middle size:80.00%  line:10.00% 
Да, и коль ты будешь там,

189
00:09:41.814 --> 00:09:42.848  position:50.00%,middle  align:middle size:80.00%  line:10.00% 
Оригинальный сериал "Netflix"
````

Where `line:` is bellow 50%.

**Comment by niksedk** [comment]
Hm, it seems to work here... I've committed the code and updated the beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

Could you re-test?

**Comment by Plazik** [comment]
I tested it and it still doesn't work for me.
I've asked friend to test it, he said it doesn't work for him too.

I don't know why. I've uninstalled stable 3.5.2 version and tested beta version again - doesn't work. I can't see an `{\an8}` tags in .ass or .srt files.

Here is some screenshots, myabe it helps you:
http://imgbox.com/4xtwwfdG
http://imgbox.com/iXJItGkY

The "Source view" tab doesn't have any information from source file (like `position:50.00%,middle  align:middle size:80.00%  line:10.00%`). Maybe there is a problem with this?

Here is screenshots from dfxp version:
http://imgbox.com/ggf0X1Au
http://imgbox.com/Xxz81JXj

**Comment by niksedk** [comment]
OK, I was able to re-produce the dfxp issue - should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.2/SubtitleEditBeta.zip

I'm still unable to find anything wrong with vtt - see line 188 in Riverdale.1x09.rus.vtt:

    {\an8}Да, и коль ты будешь там,

**Comment by Plazik** [comment]
dfxp forks fine now, thank you!

vtt still doesn't work. I've asked third friend with Russian Windows 10 - doesn't work for him too.

Here is english vtt version of subtitles, maybe it helps:
https://mega.nz/#!Ic8hzCKL!JtNTj2HJDjjhH4iHj-pW6Yy4AnKo-xTu92eGzSyGkjo

**Comment by niksedk** [comment]
1) Open file `Riverdale.1x09.eng.vtt`
2) Press `Ctrl+G` and enter 185 and press ENTER
3) Line 185 contains `{\an8}Yeah, and while you're there...`

What are you doing???

**Comment by Plazik** [comment]
I did the same http://imgbox.com/CnukzouC

No `{\an8}` tags...

**Comment by niksedk** [comment]
Are you running Build 177?
Could be a cache issue....

**Comment by Plazik** [comment]
Buid 176, re-download it and it still 176.

**Comment by niksedk** [comment]
176 is okay too here... I really don't know why it does not work for you, sorry.

**Comment by Plazik** [comment]
No problem. Thank you anyway.
