### ISSUE TITLE
Release 3.5.4

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/subtitleedit#2579]
It's time for a new release (probably a bit late), so we can get all the nice new features and fixes out :)

TODO:
- [x] Test export to images
- [x] Test "Binary image compare" OCR
- [x] Test "Batch convert"
- [x] General testing + (fixing bugs)

If you know any issue that should be included please do let us know :)

Link to latest portable beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Any chance you could take a look at the last couple of things I submitted, which all have to do with original/translation timing in translator mode? They're here: https://github.com/SubtitleEdit/subtitleedit/issues/2544 https://github.com/SubtitleEdit/subtitleedit/issues/2545 https://github.com/SubtitleEdit/subtitleedit/issues/2557

**Comment by niksedk** [comment]
@darnn: I've tried to include fixes for #2544 + #2557 in latest beta - how does it work?

**Comment by darnn** [comment]
Not well, I'm afraid:
https://github.com/SubtitleEdit/subtitleedit/issues/2544 remains the same for me (build 278). If I follow steps 1-7 and save both files, I still get this:
Translation:
1
00:00:01,000 --> 00:00:03,000
(text)

Original:
1
-00:00:01,001 --> 00:00:00,999
(text)

And then the subsequent problem described in the next steps can be reproduced as well.

As for https://github.com/SubtitleEdit/subtitleedit/issues/2557, right now when I try to import time codes, the text of the original subtitle disappears outright:
![se-translator-insert-time-codes](https://user-images.githubusercontent.com/19672444/30937235-dc61ab0a-a3de-11e7-9ba8-d16cc6b946fe.gif)

**Comment by OmrSi** [comment]
When I use Save all shortcut, i get:
![untitled](https://user-images.githubusercontent.com/20923700/30938397-8e814414-a3e2-11e7-84d7-2bf4a67ebf42.png)

**Comment by darnn** [comment]
Oh, yeah, that's what it does normally, I just mean that in the specific scenario I'm describing it only saves the translation. Unless you're saying you can't reproduce that when you follow the steps I take, as well?

**Comment by sheppaul** [comment]
Is there any reason not to follow system font size/font in main menu of subtitle edit? Under the environment using CJK fonts, the default font size which is fixed to 8 point is really hard to read it. It's really pain and hard to figure it out. At least, the font size should be 9 point and I'm using 10 point.

Please consider it.

![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/30946432-031fb722-a43f-11e7-8ad5-294cca398a72.jpg)

**Comment by xnaas** [comment]
Is it possible to get support for larger subtitle files? Sometimes a group releases their subtitles in some retarded fashion and you end up with subtitle files that are...large. An example of a recent thing I've run into is a release of [insert anime here] and the subtitle files are over 16MB...

**Comment by niksedk** [comment]
@darnn: #2544 I still cannot re-create, new fix for #2557 included in latest beta.

@sheppaul: How does latest beta look?

@xnaas: OK, that's one big sub - I've raised the max subtitle file size to 20 mb now.

Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by xnaas** [comment]
Thanks, @niksedk!  ❤️  

I was shocked too...I've never seen subtitles made in such a weird way and such massive filesizes...

**Comment by sheppaul** [comment]
@niksedk: It's fixed now for the main menu. 👍 
It would be appreciated if it is applied across all over the application.

**Comment by darnn** [comment]
I replied in the thread for #2544. With #2557 I now get the following error:
![se-import-timecode-error](https://user-images.githubusercontent.com/19672444/30977479-4c93f1a2-a480-11e7-8a7b-04a4dcab9a6e.png)

**Comment by niksedk** [comment]
@sheppaul: OK, beta with all windows fixed: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

@darnn: I've also tried yet again to fix import time codes in above beta - better?

**Comment by darnn** [comment]
Yeah, it seems to work properly now on my end.

**Comment by sheppaul** [comment]
@niksedk: unbelievable speed!. :) I've checked and I think you need to check all the changed dialog after changing the system font to 10 point. 10 point could be used widely in CJK environments so please check it if possible.

![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/30979318-4ff11fcc-a4b8-11e7-851e-7f559a58f159.jpg)

![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/30979321-5296c1d2-a4b8-11e7-8396-99bb649d86cd.jpg)

![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/30979325-549c853e-a4b8-11e7-9e36-2e85c0032155.jpg)

**Comment by OmrSi** [comment]
maybe add the possibility to add other languages to don't-break-after list?

**Comment by niksedk** [comment]
@darnn: One down... thx for testing :)

@sheppaul: thx for testing :)  - new beta up with better sized windows I hope: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
1. maybe add the possibility to add other languages to don't-break-after list?

2. when using "Remove Line breaks in short text (all except dialogs)" i only get dialogs?!
is this an error or am i not getting it right?
![untitled](https://user-images.githubusercontent.com/20923700/30992514-e9fe4fe6-a4b2-11e7-81af-b6eb19784228.jpg)

**Comment by sheppaul** [comment]
@niksedk: Wow, you're really quick. Thanks for hearing my opinion. Probably you don't feel that much. However, it's really great improvement for CJK users. Thank you so much and it's almost finished except for the font size in main window. It is still fixed to 8 or 9 points. If there is any reason to keep the size, please take an action for that too. Besides, the OK button size should be enlarged a bit in Help - About dialgo box.

See the following, this kinds of text should be 9 point at least even if it is intentionally fixed to small size. It's very hard to figure out as you may see the red box.
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/30994875-8ab3fd3a-a4f1-11e7-9018-58abb15b8182.jpg)

On behalf of CJK users, I give you my appreciation again with all my heart. Thank you!

**Comment by sheppaul** [comment]
I have one suggestion. What do you think of using system font and size by default for Subtitle font and Subtitle font size in Options - Settings - General. It seems to be fixed as Tahoma and 8 point by default.

**Comment by sheppaul** [comment]
The buttons need to be adjusted here too.

![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/30996218-1dc6be3e-a4fa-11e7-843f-6a1585bad049.jpg)

**Comment by diomed** [comment]
@OmrSi your should specify language. there are already 3 files for nobreak after list, and you can easily add your own:
look how easy is to make it in danish example:
https://github.com/SubtitleEdit/subtitleedit/blob/master/Dictionaries/da_NoBreakAfterList.xml

just make file for your language & write words in your language instead.

**Comment by OmrSi** [comment]
Thank You. :)
only number 2 then.

**Comment by OmrSi** [comment]
Speaking of "1.Remove Line breaks in short text (all except dialogs)"
and "2.Remove Line breaks in short text with only sentence"
what is the number of letters they depend on? and what's the deference?
shouldn't it be "Remove Line breaks in short text (only dialogs)"?
and shouldn't "Remove Line breaks in short text with only sentence" depend on the number of letters you set in the program?

**Comment by OmrSi** [comment]
I just tried it on an English file and it works. 
But it doesn't when using an LTR Arabic file.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

@OmrSi: Could you test the (2) stuff about remove line breaks in short texts?
"Remove line breaks in short text with only one sentence" will only un-break if not ".?!:..." are in the middle of the line.
I don't think the Arabic "don't-break-after list" is very important for next release... feel free to make a new issue, though.

@sheppaul : could you re-test the beta?
Where is the font not correct in the main window?
I'm not really sure about the default font... Tahoma is nice because uppercase "i" (I) and lowercase "L" (l) looks different.

**Comment by OmrSi** [comment]
well, @diomed told me how to add Arabic "don't-break-after list". So, you don't have to add and thing about this.

Regarding, "Remove line breaks in short text with only one sentence"
I created a new file and wrote only one sentence in arabic, with no ".?!:..."
and I wrote less than 42 the broke it, when using "Remove line breaks in short text with only one sentence" the line doesn't show up in the fix list.

As for "Remove Line breaks in short text (all except dialogs)"
When using Arabic i only shows lines with dialogs, whether if i used Arabic in LTR writing or reversed it.


As for Use system default font for all windows, well, as you said the font you used before was perfect in size and shape...

**Comment by sheppaul** [comment]
@niksedk: It's not a big deal and I think it's enough. What I'm saying is there are several parts which is not following the system font size. Except for the red box, the font size seems to be fixed to 9 point.
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31041298-ba4bc578-a5cd-11e7-96c8-a5ff22b39581.jpg)

> I'm not really sure about the default font... Tahoma is nice because uppercase "i" (I) and lowercase "L" (l) looks different.
Actually, it doesn't matter as we can change it in preferences. I'm just saying default values. Mostly, the default system font of any Windows would have the best fit to use in their environment. Tahoma is good  for English but I wonder if it should be a default font for all the cases.

**Comment by sheppaul** [comment]
For comparisons, see the followings

System default font and size in Korean Windows (i & l is clearly distinguishable)
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31041415-ec6eafaa-a5cf-11e7-8eb4-53596fd3962e.jpg)

Tahoma, 8 point
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31041419-edd741fe-a5cf-11e7-9b73-dfc533abdd50.jpg)

Tahoma, 10 point. Closely look the size of Tahoma in the screenshot and compare it with the first screenshot after clicking each one. Tahoma 10 does not match the default system font size.
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31041420-efaf340a-a5cf-11e7-8f8c-b9172bd4baae.jpg)

**Comment by niksedk** [comment]
@sheppaul: More controls om the main window now uses the default font: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.3/SubtitleEditBeta.zip

**Comment by OmrSi** [comment]
Should I make a separate problem about this to leave space for other things here?

**Comment by sheppaul** [comment]
@niksedk: I'd like to see what's changed but I'm in hosptial. It'll take several days here. Thank you for spending your precious time and the work you've done.

**Comment by Elheym** [comment]
@niksedk Could you add the ability to save resizing or position of the "Multiple replace" window in the settings file. So that after exit from SE any changes in size or position of this window can be saved in this configuration file. Like on this screens:
before changing the size / position of the window (by default)
![before](https://user-images.githubusercontent.com/14152676/31046099-4407181c-a5fb-11e7-9c6c-358aba5f532a.png)
after changing the size / position of the window (as requested)
![after](https://user-images.githubusercontent.com/14152676/31046112-9035085c-a5fb-11e7-8526-5fb6e8fde8a8.png)

**Comment by OmrSi** [comment]
I checked "Remove Line breaks in short text with only sentence" again with arabic, it works for very short lines, but "Remove Line breaks in short text (all except dialogs)" still only shows with dialogs in Arabic.
Is there an option to make it remove line break if the two lines merged are shorter than the number of letters in one line you determined?

**Comment by sheppaul** [comment]
I'm back.  Ahh, If I have some more time before releasing new version....
The buttons of main windows are not adjusted at all. So the button text is a bit crushed.

Please adjust the buttons below in next version. Thanks. 👍 

![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31109104-b190b106-a838-11e7-8a58-5e54438ad189.jpg)
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31109106-b3dc93c6-a838-11e7-99c3-748252244b5b.jpg)
![Image of Yaktocat](https://user-images.githubusercontent.com/18511443/31109109-b5565818-a838-11e7-901e-0f9429e3dc00.jpg)
