### ISSUE TITLE
Language not always appended on Batch convert

### ISSUE THREAD

**Issue by Rouzax** [SubtitleEdit/subtitleedit#3297]
With Subtitle Edit 3.5.8 - Batch converter when processing a file it does not always append the language name of the subtitle
```
Subtitle Edit 3.5.8 - Batch converter

1: The.Goldbergs.2013.S06E12.1080p.WEB.H264-METCON.mkv -> The.Goldbergs.2013.S06E12.1080p.WEB.H264-METCON.srt... done.
```

When looking at the actual MKV it is there
![image](https://user-images.githubusercontent.com/4103090/51313028-dda62280-1a4c-11e9-8123-b207c1223e1d.png)

**Comment by niksedk** [comment]
Yes, I never got around adding this... should now work in latest beta though: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
It did work if there were more than 1 subtitle in the file.
Will give it a try with the new beta. 
Thank you!

**Comment by Rouzax** [comment]
@niksedk: Just tried it but it still doesn't export with the language code appended.
Version 3.5.8.106
```
1: The.Big.Bang.Theory.S12E13.1080p.WEB.H264-AMCON.mkv -> C:\TEST\The.Big.Bang.Theory.S12E13.1080p.WEB.H264-AMCON.srt... done.
```
![image](https://user-images.githubusercontent.com/4103090/51372262-d76f7f00-1afc-11e9-956e-974db3c01a23.png)


Do you want me to provide an MKV with the subtitle but without audio and video?

**Comment by niksedk** [comment]
Thx - should be fixed via above commit - and in latest beta binary: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip

**Comment by Rouzax** [comment]
@niksedk: Just tested but it is still not appending the language code
Version 3.5.8.108
```
1: The.Big.Bang.Theory.S12E13.1080p.WEB.H264-AMCON.mkv -> C:\Test\The.Big.Bang.Theory.S12E13.1080p.WEB.H264-AMCON.srt... done.
```

**Comment by OmrSi** [comment]
I think it only appends if there was more than one file, as it should, in my opinion...

**Comment by Rouzax** [comment]
That was already the behaviour previously,

```
Subtitle Edit 3.5.8 - Batch converter

1: The.Grand.Tour.S01E01.1080p.WEBRip.X264-DEFLATE.3.eng.mkv -> C:\TEMP\Torrent\PROCD\TV\The.Grand.Tour.COMPLETE.S01.1080p.WEBRip.X264-DEFLATE[NORAR]\The.Grand.Tour.S01E01.1080p.WEBRip.X264-DEFLATE.3.eng.srt... done.
1: The.Grand.Tour.S01E01.1080p.WEBRip.X264-DEFLATE.4.eng.mkv -> C:\TEMP\Torrent\PROCD\TV\The.Grand.Tour.COMPLETE.S01.1080p.WEBRip.X264-DEFLATE[NORAR]\The.Grand.Tour.S01E01.1080p.WEBRip.X264-DEFLATE.4.eng.srt... done.
```

**Comment by niksedk** [comment]
Your sample file `The.Big.Bang.Theory.S12E13.1080p.WEB.H264-AMCON.(subsonly).mkv` gave `The.Big.Bang.Theory.S12E13.1080p.WEB.H264-AMCON.(subsonly).eng.srt` so that seems to work...

**Comment by Rouzax** [comment]
Do you want me to share the full file?

**Comment by Rouzax** [comment]
So it was a miscommunication I was talking about the CLI feature.

**Comment by niksedk** [comment]
Ah, sorry, should have seen that... beta updated where cmd line convert should work more like batch convert: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.8/SubtitleEditBeta.zip
