### ISSUE TITLE
OCRFixReplaceList_User.xml: <BeginLines> does not work

### ISSUE THREAD

**Issue by Maitch** [SubtitleEdit/subtitleedit#3850]
Hello

I was trying to come up with a different solution to issue #3841.  Basically, "... finde fødselsdagsbarnet" turns to ". Finde fødselsdagsbarnet"

I figured that every time I have a line that starts with a single dot and space, then it should be three dots and a space. So I added the following to dan_OCRFixReplaceList_User.xml

```
<BeginLines>
    <Beginning from=". " to="... " />
    <Beginning from="- . " to="- ... " />
</BeginLines>
```
This changed nothing.

So now I added the same lines to dan_OCRFixReplaceList.xml, so we had the following:
```
<BeginLines>
    <Beginning from="-] " to="- I " />
    <Beginning from="- ] " to="- I " />
    <Beginning from="] " to="I " />
    <Beginning from="-| " to="- I " />
    <Beginning from="- | " to="- I " />
    <Beginning from=". " to="... " />
    <Beginning from="- . " to="- ... " />
</BeginLines>
```
This worked.

So my question is, does BeginLines work in the user xml?

**Comment by Maitch** [comment]
By the way, if I add the above to BeginLines and the following to EndLines, I will have solved most of my three dots issues. The VobSub from #3841 is solved this way. 

 ```
<EndLines>
    <Ending from=" ." to=" ..." />
</EndLines>
```

**Comment by niksedk** [comment]
Hm, this has apparently never been working so thx for reporting the issue :)
Fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.11/SubtitleEditBeta.zip

**Comment by Maitch** [comment]
<RegularExpressions> does still not seem to work in dan_OCRFixReplaceList_User.xml in the beta.

**Comment by xylographe** [comment]
That beta does not yet include commit 46782409f66a45391be19ada6ad13fb4e1d9d3ee.

Try **`SE-3.5.11.126.7z`** from [this DropBox folder](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0).

**Comment by Maitch** [comment]
SE-3.5.11.126.7z works. Good work!
