### ISSUE TITLE
OCR spell checking does not work

### ISSUE THREAD

**Issue by Signy13** [SubtitleEdit/subtitleedit#4110]
With the last version of Subtitle edit #4105 another bug showed - OCR spell checking is not workin now. Even though there is a misspelled word, it does not show as an unknown word:
![SubtitleEdit_18](https://user-images.githubusercontent.com/18901924/79073349-58103180-7ce6-11ea-83b6-93923349d141.png)
I am sure it is related with the missing `ThreeLetterISOLanguageName`, sorry for that...

**Comment by niksedk** [comment]
Seems to work here... could you attach a English example that does not work?
Is it only a problem when running via Wine?

**Comment by Signy13** [comment]
@niksedk thank you for response.
If this problem is related to #4105 with missing `culture` under Wine + .NET then SE can work under different systems. 

I am sorry that I did not noticed this yesterday while I was testing #4105 - my testing video was pretty short and I thought that there are no unknown words any more.

I prepared new testing video and did some more tests:
Wine 3.21 - working as usually (not affected by #4105 )
![SubtitleEdit_21](https://user-images.githubusercontent.com/18901924/79097707-afeb7e80-7d60-11ea-8fa1-3f210205c4fb.png)

Wine 5.5 + .NET 4.7.1
* Czech dictionary selected - not working (my first notice of this bug).
![SubtitleEdit_22](https://user-images.githubusercontent.com/18901924/79097786-dad5d280-7d60-11ea-9223-e20c16010492.png)
* English dictionary selected - big surprise - working. The only weird thing is, that subtitle lines (for example nr. 2) are green, although there is a lot of unknown words.
![SubtitleEdit_23](https://user-images.githubusercontent.com/18901924/79097898-27b9a900-7d61-11ea-9cc7-426ebfda3e3e.png)
* None dictionary selected - even bigger surprise - working as if the Czech dictionary was selected. It found same words as Wine 3.21 with Czech dictionary selected.
![SubtitleEdit_24](https://user-images.githubusercontent.com/18901924/79098120-8aab4000-7d61-11ea-8483-bd3011f71df6.png)

It looks as if there is something between dictionary selection and spell checker affected by #4105.

**Comment by niksedk** [comment]
Argh, lines with many errors are actually colored green... fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
OK, added the correct ISO codes that Tesseract actually uses... that should help!?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
Thank you for quick fixing the colour of lines with many errors :-) .
I tested the last version but it the behaviour is still the same. 
The selection for Tesseract works. 
After some testing I can see connection between Tesseract language selection and SPell checking selection.
**Under Wine 3.21** (where `culture` works as usually)
* if there is selected the same language for Tesseract and spell checking then spell checking works:
![SubtitleEdit_26](https://user-images.githubusercontent.com/18901924/79116033-b17c6d00-7d87-11ea-9e6c-48398d4041aa.png)
* if there is selected the different language for Tesseract from language for spell checking then spell checking does not work:
![SubtitleEdit_27](https://user-images.githubusercontent.com/18901924/79116185-10da7d00-7d88-11ea-9e3f-c52d2b22f298.png)

**Under Wine 5.5 with .NET 4.7.1** (where `culture` does not work)
* if there is selected some file for Tesseract and spell checking has no language then spell checking works (although it should not work)
![SubtitleEdit_28](https://user-images.githubusercontent.com/18901924/79116519-fce34b00-7d88-11ea-88d7-15b75c016168.png)

Selection of language/.traineddata file for Tesseract should be independent from selection for spell checking.

**Comment by niksedk** [comment]
Beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

Spelling dictionary will be changed, when changing Tesseract language and this language has a matching spelling dictionary (if not match, current spelling dictionary will be kept).

**Comment by Signy13** [comment]
Than you for update. I did some tests:

**Wine 5.0 with .NET 4.0** (where `culture` does not work)
* Only Tesseract language: "eng" changes spell checking dictionary to "English (United States) en_US.
* With Tesseract language: "ces" there is no change of spellchecking dictionary (which is OK because the language was not properly recognized and it is no trouble for a user).

OCR function itself:
* With Tesseract language: "ces" (or any other language) and spell checking dictionary: "none" OCR works (that is OK) and recognizes Czech words (which is not OK - it should not, for "none" dictionary).
* With Tesseract language: "ces" and spell checking dictionary: "English (United States en_US)" OCR works and recognizes many unknown words - that is perfectly OK.
* With Tesseract language: "ces" and spell checking dictionary: "Czech (Czech Republic) cz_CZ" (or "cs_CZ_old" dictionary) appears a Thread Exception (see bellow). When I hit "Ignore" button, exception disappears and I have to stop OCR manually. 
* With Tesseract language: "eng" and spell checking dictionary: "Czech (Czech Republic) cz_CZ" (or any other non english dictionary) appears the same Thread Exception.
![SubtitleEdit_33](https://user-images.githubusercontent.com/18901924/79141202-975b8280-7db9-11ea-96b8-5ed6276c9fd7.png)

Conclusion:
* Spell checking dictionary "none" behaves as "Czech (Czech Republic) cz_CZ" (or maybe "cs_CZ_old").
* Spell checking dictionary "English (United States en_US)" works well.
* Other Spell checking dictionaries do not work.

In the next part:
* TL means Tesseract language, 
* SD means Spell checking dictionary.

Wine 3.21 (where culture works)
* When I change TL to "English" then SD changes to "English (United States)" en_US - that is OK.
* When TL != "Czech" and SD != "cs_CZ_old", a change TL to "Czech" changes SD to "Czech (Czech Republic) cz_CZ" - which is OK.
* When TL != "Czech" and SD = "cs_CZ_old", a change TL to "Czech" does not change SD (remains "cz_CZ_old") - that is probably not OK.
* Swithing TL between other unknown languages or languages without proper SD does not change SD - which is OK.

OCR function itself seems to be working correctly according to selected TL language and SD. Even if there is unknown TL it works well according to selected SD.

I certainly underestimated how much is SubtitleEdit influenced by the not working `culture` - I am sorry for all the troubles you have with the  #4105 workaround :-( .

**Comment by niksedk** [comment]
Strange... everything I test on Windows works perfectly - is that also the case for you?
Made some minor fixes but I don't really know what's wrong, so it really hard to fix anything!
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by niksedk** [comment]
Found a few more places where the "ThreeLetterISOLanguageName" was used... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
@niksedk I understand how difficult is fixing problems which do not have an inpact in your environment and you can not debug it in an easy way - it is like searching a handful of needles in a haystack, when you have to find all of them. I appreciate this difficult work.

By me SubtitleEdit is generally working under the old Wine 3.21 with its internal Mono. I test even situation when there is an unknown tessdata file (for example `bflmpsvz.traineddata`) and an unknown dictionary file (there are two different dictionary files for my language, one of them i renamed to: `cs_CZ_old.aff` and `cs_CZ_old.dic` but it is better when SubtitleEdit works with any unknown name).

Thank you for this version. I ran it under Wine 5.0 + .NET 4.0 (where was the `ThreeLetterISOLanguageName` supposed not to work). The biggest surprise of this version: you have made Tesseract language comboBox working in an usual way - it is the first time when I can see there "Czech" and not "ces" in Wine 5.0 + .NET (which was the workaround #4105 ):
![SubtitleEdit_37](https://user-images.githubusercontent.com/18901924/79188941-ba6d4d00-7e20-11ea-85c4-b601e4ef958d.png)

In the next part:
* TL means Tesseract language
* SD means Spell checking dictionary

1) When I start SubtitleEdit for the first time then TL = "bflmpsvz" and SD is empty. Is it correct that SD is empty? "None" might be better.
Eventhough SD is empty, it behaves as if there was SD = "Czech (Czech Republic) cs_CZ" (I can see it, because I removed the word "důvod" from this dictionary):
![SubtitleEdit_36](https://user-images.githubusercontent.com/18901924/79188730-2602ea80-7e20-11ea-99a7-6cc9ae38cf1d.png)
BTW: "Czech (Czech Republic) cs_CZ" is the first real dictionary in the SD combobox:
![SubtitleEdit_40](https://user-images.githubusercontent.com/18901924/79193328-b34b3c80-7e2a-11ea-9664-8d50d7374b52.png)


2) If there are known TL and SD then Switching TL changes SD correctly. For example if TL = "English" and SD = "English (United States) en_US" and I switch TL to Czech then SD changes to "Czech (Czech Republic) cs_CZ"
3) If TL = "bflmpsvz" and SD = "cs_CZ_old" and I swith TL to "Czech" then SD remains "cs_CZ_old". That is a bit surprising - why not "Czech (Czech Republic) cs_CZ"?
4) I created dictionary files `unknown.aff` and `unknown.dic` and this behaves in a weird way:
* If TL = "Czech" and SD =  "Czech (Czech Republic) cs_CZ" and I switch SD to "unknown" then SD remains  "Czech (Czech Republic) cs_CZ" - this is weird.
* If TL ="English" and SD = "English (United States) en_US" and I switch SD to "unknown" then SD remains  "English (United States) en_US" - the same behaviour as in the previous point.
* If TL ="German" and SD = "English (United States) en_US" (I have not got German dictionary) and I switch SD to "unknown" then SD = "unknown". This is correct.
* If TL = "Czech" and SD =  "Czech (Czech Republic) cs_CZ" and I switch SD to "cs_CZ_old" then SD changes to "cs_CZ_old". This is correct.

So why I can not switch SD to "unknown" dictionary when there is a known dictionary for selected TL?

5) OCR works, but the spell checking probably uses a different dictionary from the selected one:
* If TL = "Czech" and SD =  "Czech (Czech Republic) cs_CZ" then spell checking dictionary is "Czech (Czech Republic) cs_CZ"  (correct).
* If TL = "Czech" and SD = "English (United States) en_US" then spell checking dictionary is "English (United States) en_US"  (correct).
* If TL = "Czech" and SD =  "cs_CZ_old" then spell checking dictionary is "Czech (Czech Republic) cs_CZ"  - that is wrong (I can see it, because cs_CZ_old has the word "důvod" but I removed word "dceři":
![SubtitleEdit_38](https://user-images.githubusercontent.com/18901924/79191230-65343a00-7e26-11ea-8022-6898b1f058c3.png)

I did a quick check under Wine 3.21 (where `ThreeLetterISOLanguageName` worked all the time) and found the same behaviour as above. Now it looks like as if you really fixed the problem which started #4105 . 
Maybe there was a bit another problem than `ThreeLetterISOLanguageName`.

**Comment by niksedk** [comment]
The reason you can see Czech (yay) is that I added all ISO 169.2 languages here:
https://github.com/SubtitleEdit/subtitleedit/blob/master/libse/Iso639Dash2CountryCode.cs

Hopefully fixed the issue with loading a spell check directory in latest beta:
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
@niksedk : With the Czech in Tesseract language I hoped in a miracle and you fixed it in this simple way :-) Nice.
I looked at some of your commits - that is hell lot of work, thank you :-)

I tested it and I found only one thing:
* If Tesseract language (TL) = "Czech" and Spell checking dictionary (SD) = "none" then it behaves as if SD = "Czech (Czech Republic) cs_CZ"
![SubtitleEdit_41](https://user-images.githubusercontent.com/18901924/79238673-f7acfb80-7e6f-11ea-9ae9-d9968e4ccdfe.png)
With TL = "English" it probably spell checks English dictionary.  I think that with SD = "none" it should ignore spell checking at all.

Except that it looks OK - I even tested spell checking in the main SubtitleEdit window and it looks OK.

**Comment by niksedk** [comment]
thx for testing :)
It was very nice to  "color many unknown words" issue fixed too.

Is latest beta still doing spell check with "None" ?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip

**Comment by Signy13** [comment]
@niksedk you are rigth, I like that you fixed accidentally found small issues too :-)
Another testing and yes, even the latest beta still does checking with SD = "None".
I tried to realize which dictionary is actually used when SD = "none" is selected" but only now did I notice that "Unknown words" are not ordered by line number but by the time the line was OCRed... I need to do these tests again - tomorrow.
Anyway thanks for your effort :-)

**Comment by niksedk** [comment]
And... beta updated: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.5.14/SubtitleEditBeta.zip
(some minor checks and never use the CultureInfo.ThreeLeterISOLanguageName directly anywhere)

**Comment by Signy13** [comment]
Thank you - I tested it again and this fix helped. Now Spell checking dictionary (SD) = "none" works as supposed. Actually the whole selection of spell checking dictionary.

In this version (and previous too) randomly after a couple of starting OCR (without saving - just  start OCR, change settings and start OCR and again and again) can happen that OCR is suprisingly long - like 1 row after two minutes or longer. Sometimes I kill SubitleEdit without waiting till the end (I use a piece of a movie with just 5 lines). It helps just close OCR dialog with the button "Cancel" and open the same MKV movie again and it is working... But that would be probably for another bugreport.

Thank you very much for all the time you spend with this CultureInfo workaroud - I appreciate that you have made it although the bug is somewhere in Wine when it runs .NET.
And I am glad that besides the problems is SubtitleEdit better software now :-) .
