### ISSUE TITLE
Double italics

### ISSUE THREAD

**Issue by Charvelx04** [SubtitleEdit/subtitleedit#5493]
I have also noticed that, either a regression or "feature", maybe something that was removed perhaps?

Fix Common Errors no longer includes removing a double set of italics in a single line.

![123](https://user-images.githubusercontent.com/35577096/142145769-77d37acc-14b1-4ebe-9285-25875ae62f1e.jpg)

**Comment by niksedk** [comment]
Thx for the info :)
Should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.3/SubtitleEditBeta.zip

**Comment by Charvelx04** [comment]
I will give that beta a try... thank you for one of the fastest responses I've ever seen!

T.

**Comment by Charvelx04** [comment]
Unfortunately, I'm still seeing it.

Is there an option I need to check/uncheck? I don't see where we can manually edit OCR rules.


![Untitled](https://user-images.githubusercontent.com/35577096/142294310-a5456044-e447-4270-b53d-1f409dd05d73.jpg)

**Comment by Charvelx04** [comment]
Okay... not sure if this was the right selection, or what.. but when I checked the box "Normalize Strings" it seems to be working again. 
I don't know. But it is working, and I'm not going to look that gift horse in the mouth.

Thank you for the help. :)

**Comment by musicadi** [comment]
Hi, I think I found a problem, which might be caused by fixing this one :)

When a subtitle event has two italics tags (one for each line), SE seems to automatically remove one of them. I didn't notice this before. Running version 3.6.4 now

**Comment by Charvelx04** [comment]
> Hi, I think I found a problem, which might be caused by fixing this one :)
> 
> When a subtitle event has two italics tags (one for each line), SE seems to automatically remove one of them. I didn't notice this before. Running version 3.6.4 now

Correct. It's just poor coding on the original creation of the sub. There's just no need to have each line with their own set of italic tags. 
Some movie players, like VLC.. will show onscreen italics with just the first part of that tag, <i> , but it's just good technique to have it complete. In fact, most tags are like this... ex: <b> for bold... will show BOLD text even without the closing tag </b>. It just looks ugly under the hood.

**Comment by musicadi** [comment]
@Charvelx04 yes, I know, it makes no sense having two tags in the same event, if the whole text should be italics, except maybe for "visual" reasons. However, I still think the double tags shouldn't be automatically removed, because there could be situations when you only need two separate words to be in italics

**Comment by Charvelx04** [comment]
When it comes to tags.. I've pretty much seen it all.

Single tags.. like <i> without the </i> still shows italics onscreen. (SE
will add the missing </i> tag)
Double italics... for the whole sentence, and they are only there because
of the break in the sentence. These are not needed. (SE removes the second,
and combines the two)
Dialog italics. Typically one sentence in italics the other isn't. Ex:
talking to someone over a radio. (SE leaves these alone, unless you split
before editing, then it removes the dialog mark)
<i>- We're not here right now.</i>
- Copy that.

More often than not, I will split dialogs like this as onscreen, they don't
look very aesthetically pleasing. In fact, in most cases, almost all
dialogs can be split as there is a gap between what two people onscreen are
saying.. but I will keep all dialogs for words being spoken at the exact
same time.

**Comment by Charvelx04** [comment]
If you're thinking what I think you're thinking, are you referring to, say a name of a ship within an italicized sentence?

<i> This is the ghost ship, </i> Mariner One. <i>She's been lost at sea for years.</i>

That will remain intact as is... leaving "Mariner One" not in italics. Personally, I can't stand this.. but I understand, as it has it's opposite sentence structure such as:

This is the ghost ship, <i>Mariner One.</i> She's been lost at sea for years. 

Some like to have names like that in italics... it's no never mind to me either way, but having italics all the way around, and one word not, it can look ugly onscreen depending on what font your media player is using.

**Comment by musicadi** [comment]
@Charvelx04 thank you for your replies. As far as I'm concerned, formatting could be either way :) I am translating some subtitles and I need to keep the structure of the original file, that's why I thought it would be a good idea to make he removal of the second tag optional (maybe turned on by default, so it would be seamless)
