### ISSUE TITLE
Unexpected behavir (perhaps) on pasting subtitles or text into a completely new file

### ISSUE THREAD

**Issue by darnn** [SubtitleEdit/subtitleedit#5686]
SE 3.6.4 beta 265.
1. Create a new file. Now copy the contents of a random text file with a large number of lines, and paste into SE. It will start parsing each line as a subtitle and creating individual timecodes for them, and it can take quite a few seconds before it finishes. The first time I did this it even froze.
2. Same thing, create a new file. Copy the contents of an SRT file and paste into SE. This happens instantaneously, as it should. Now undo the paste. The timecode of the "first", nonexistent subtitle stays unchanged from the last thing it was before the undo action.

**Comment by niksedk** [comment]
I tried to look at the performance - how is this: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

for 2, could you explain more - do use screenshots + sample files.

**Comment by darnn** [comment]
The performance fix is great. As far as 2 goes, this might just be a more general thing, but:
When you create a new file, the "first" subtitle in it is one that doesn't have a number in list view, and has a start time of 00:00:00:00 and a duration of 0.00:
![se-0subtitle01](https://user-images.githubusercontent.com/19672444/149036520-2b887959-cd62-45be-99bd-734b3e10966c.png)

If you then paste text as in 1 in my original post, the start time and duration will change to the automatically generated ones for the new first subtitle, which is now selected in list view:
![se-0subtitle02](https://user-images.githubusercontent.com/19672444/149036537-676df639-b6a1-483d-8b14-1cdc1414b86d.png)

If you then undo the paste operation, the subtitle that doesn't appear in list view will now have the start time and duration of the previous subtitle that had been selected:
![se-0subtitle03](https://user-images.githubusercontent.com/19672444/149036625-0be9691b-141e-4dd3-a2cb-f9ba2e4a984f.png)

Now, if you click the textbox and start typing, and then use the insert after or insert before keyboard shortcuts, everything you've typed will disappear, and you'll be left with only one subtitle. This is what it looks like before "insert after":
![se-0subtitle04](https://user-images.githubusercontent.com/19672444/149037153-30e16602-1d3e-4bc7-ba87-148733049be9.png)

And this is what it looks like after:
![se-0subtitle05](https://user-images.githubusercontent.com/19672444/149037160-1b0eb512-63b3-4c2f-b5a5-233e83664b38.png)

**Comment by niksedk** [comment]
thx for explaining :)

It's seems to about about the "disabled edit controls" when SE is all empty... how is this?
https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Much better! The only other thing I noticed is this:
Copy several lines of text to the clipboard. In SE, create a new file. Click on the textbox to focus on it. Now create a new file again.  Paste. The last line of the copied text will now appear in the greyed-out textbox.

**Comment by niksedk** [comment]
OK, thx for testing - what SE does depends on the amount of text and number of lines... tried to tweak it a little: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Actually, this still seems to happen under certain circumstances...
Copy text. Create a new file in SE. Close SE and then open it again. Click textbox. Create new file. Paste. Up to this point, everything works as expected. Now click the textbox again. Create new file (don't save changes). Paste. The same thing as in my previous comment happens. But it's not the end of the world if you don't feel like messing with it further, it doesn't really affect much.

**Comment by niksedk** [comment]
Could you provide more details?

**Comment by niksedk** [comment]
Also, clicking on the text box will create a new empty subtitle now when SE has no subtitle lines.

**Comment by darnn** [comment]
So. Copy some text into the clipboard (subtitles, just text with no timecodes, anything).
Now, let's say you're starting with a subtitle file already open and saved, like this:
![se-paste01](https://user-images.githubusercontent.com/19672444/149558102-44166748-b85a-47cd-87bd-6f194231923c.png)

Create a new file  (using either the keyboard shortcut or the icon, doesn't matter). Now you have a blank file, and when you close SE and open it again, it will open on a blank file. Do this. Now paste the text. This will create individual subtitles with automatically generated timecodes for each line, as intended:
![se-paste02](https://user-images.githubusercontent.com/19672444/149558615-41104c3a-53af-45a5-81da-70949467679f.png)

Now, click the textbox to focus it. Create a new file again. You'll be prompted to save the changes to the previous file. Click no. Now you once again have something that looks like this:
![se-paste03](https://user-images.githubusercontent.com/19672444/149558960-f973a872-4bf9-486e-b40c-8d36c26fff45.png)

Now paste the text again. This happens:
![se-paste04](https://user-images.githubusercontent.com/19672444/149559341-fda287b6-9188-452a-b14a-1db545e95618.png)

**Comment by niksedk** [comment]
OK, finally saw it... should be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
It still happens for me if you add another step of new file and then paste. That is:
Make a new file and close SE and then open it again. Paste. Make a new file (don't save changes). Paste. Click textbox. Make a new file. Note that SE doesn't ask whether changes should be saved this time, though it should. Now, in the new file, if you paste the text appears greyed out in the textbox again.

![SE-GIF 1-15-2022 4-20-53 PM](https://user-images.githubusercontent.com/19672444/149625027-8474f60f-079a-41a3-8348-fe797dda2941.gif)

**Comment by niksedk** [comment]
He, I simply cannot re-create this... you provide even more exact steps + the actual text?

**Comment by darnn** [comment]
Sure. 
The text doesn't matter, so I just used a lorem ipsum generator to get this:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec gravida placerat quam ac molestie. Praesent metus sapien, ornare in urna et, vulputate tristique felis. Mauris mollis metus mauris, et tincidunt felis tincidunt condimentum. Nunc vel nisl luctus, porttitor risus at, vulputate sem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam odio dolor, ornare eget odio quis, efficitur ultrices nisi. Sed commodo lectus elementum ante ultricies ultrices. Mauris vel porttitor enim, id eleifend ligula. Nulla convallis non purus eu maximus. Nullam vitae elit in purus cursus ultrices. Aenean varius nulla vel nisl faucibus maximus. Ut in tempor nulla. Sed vel posuere tortor. Integer posuere eros in cursus blandit. Donec auctor tellus vitae fringilla dignissim. Quisque eu vulputate augue.

Cras in tempor massa. Nulla facilisi. Proin vitae pharetra quam. Vivamus pellentesque mi leo, vel imperdiet ante tincidunt vel. Proin fermentum enim dui, ut venenatis ex suscipit sit amet. Mauris in condimentum ipsum, eget molestie libero. Etiam dui neque, porttitor non leo vitae, porttitor auctor nunc. Maecenas porta suscipit cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

The steps with it are slightly different but the behavior is the same overall. It goes like this:
Copy the above two paragraphs into the clipboard. In SE, switch to RTL mode and frame timecode mode (just to be on the safe side, since that's how it is here). Click the textbox, and then press left ctrl+left shift in order to change the text direction in the textbox to left-to-right. The cursor should now be on the left. Create a new file using the keyboard shortcut. Exit SE. Open SE again. Paste (using ctrl+V). You will get something that looks like this:
![se-paste06](https://user-images.githubusercontent.com/19672444/149661558-9181ce48-70f7-4d2d-8854-1ca7cea99448.png)


Now create a new file using the keyboard shortcut again. You will get a dialog box asking whether you should "save changes to untitled". Using the keyboard (if you use the mouse, this might not work), navigate to "no" and press enter. You will have a window with a blank file again:
![se-paste07](https://user-images.githubusercontent.com/19672444/149661338-f07a96c9-b53f-46e8-aff4-6e7b3ab1e58c.png)

Paste. Note that this time the text's alignment seems different (maybe a different kind of textbox is invoked?):
![se-paste08](https://user-images.githubusercontent.com/19672444/149661644-eff0317a-0470-47b2-bd82-510a5b06d360.png)

Click the textbox, around the first L, to focus on it. Now, again, create a new file using the keyboard shortcut. Paste. Things will now look like this:
![se-paste09](https://user-images.githubusercontent.com/19672444/149661719-6bf144d1-4acc-4335-b3d3-c5d6f00086b2.png)

I'm also attaching my settings.xml with the same window size that I was using, in case that affects it.
[Settings.xml.txt](https://github.com/SubtitleEdit/subtitleedit/files/7877013/Settings.xml.txt)

Note, again, that after the second time the text is pasted, when you're creating a new file, SE is not even asking you to save, so clearly something is already different. The fact that the alignment of the text changes between the first time you paste it and the second suggests to me something's different about the type of textbox that gets created the second time, but I'm just guessing.

**Comment by niksedk** [comment]
Thx for explaining for me - I could not re-create it without your settings (probably the right-to-left), so it should be fixed here: https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.4/SubtitleEditBeta.zip

**Comment by darnn** [comment]
Seems to be fixed here as well! The "save changes to untitled" dialog remains inconsistent, but I don't think that really makes any kind of difference. Feel free to close.
