### ISSUE TITLE
Color problem in vtt format

### ISSUE THREAD

**Issue by mbas-rtbf** [SubtitleEdit/subtitleedit#9439]
When I convert a subtitle file with colors from stl format to vtt format on the command line, I get a file with badly closed tags.

![Image](https://github.com/user-attachments/assets/656dfdcb-c563-4101-b60f-83c186d8c83e)

On the other hand, converting the same stl file to srt format works fine.

![Image](https://github.com/user-attachments/assets/37679f40-3c1c-4990-b7a5-0c6e20c7e581)

**Comment by niksedk** [comment]
Could you attach an input file, that I can re-create this issue with?

**Comment by mbas-rtbf** [comment]
@niksedk you will find the input file here: https://cloud.rtbf.be/s/CRrC8iJQPQG5XZN
Thanks

**Comment by niksedk** [comment]
Looks okay here:

````
>subtitleedit /convert a.stl srt
````

````
10:00:00,080 --> 10:00:31,040
<font color="Magenta">...</font>

2
10:00:44,680 --> 10:00:46,920
<font color="Yellow">-Je comprends pas pourquoi</font>

````

**Comment by niksedk** [comment]
STL color to WebVTT color should now be fixed in latest beta: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip

**Comment by mbas-rtbf** [comment]
Perfect, thank you @niksedk

**Comment by mbas-rtbf** [comment]
Hello @niksedk , I see that the typo correction isn't satisfactory.
The same font problem still exists in the case of multiple lines.

![Image](https://github.com/user-attachments/assets/bec54305-ecf2-471e-baad-cf1eb703f9ee)

The "c.ffff00ff" syntax has no effect on the color; the player always displays the text in white.

input stl : https://cloud.rtbf.be/s/4eDWnFNdry6epFd

Thanks.

**Comment by niksedk** [comment]
Beta updated with some webvtt fixes: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.11/SubtitleEditBeta.zip

The "c.ffff00ff" syntax works fine here for me in VLC.
